version: '3.9'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: isheet:${ISHEET_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      ISHEET_HOST: 0.0.0.0
      ISHEET_DB_FILE: /db_data/db.sqlite3
    volumes:
    - isheet-db-data:/db_data/

  taskiq-worker:
    <<: *main_app
    labels: []
    command:
    - taskiq
    - worker
    - isheet.tkq:broker



volumes:
  isheet-db-data:
    name: isheet-db-data
